spring:
  application:
    name: jokes
  boot:
    admin:
      client:
        instance:
          prefer-ip: true
        url:  ${SPRING_ADMIN:http://localhost:8080/}


management:
  endpoints:
    web:
      exposure:
        include: "*"

