FROM openjdk:17-jdk-slim
MAINTAINER baeldung.com
COPY target/organization-service-0.0.1-SNAPSHOT.jar organization-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/organization-service-0.0.1-SNAPSHOT.jar"]
