spring:

  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5444/cats-api
    password: admin
    username: admin
  jpa:
    show-sql: true
  boot:
    admin:
      client:
        url: "http://localhost:8080/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8081


