version: '3'

services:


  ostock-db:
    image: postgres:12
    container_name: postgres12
    restart: always

    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ostock_db
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
      - postgres_sql:/var/lib/postgresql/data
      - /Users/vasylkorol/backaps:/var/opt/postgresql/backup

    networks:
      backend:
        aliases:
          - "database"



  config-service:
    image: config-service
    ports:
      - "8071:8071"
    environment:
      ENCRYPT_KEY: "secretkey"
    networks:
      backend:
        aliases:
          - "config-service"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5



  eureka-service:
    image: eureka-service
    ports:
      - "8070:8070"
#    depends_on:
#      ostock-db:
#        condition: service_healthy
    networks:
      backend:
        aliases:
            - "eureka-service"


  license-service:
    image: licence-service
    ports:
      - "9003:9003"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
    depends_on:
      - ostock-db
      - config-service

    networks:
      - backend
  organization-service:
    image: organization-service
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
    networks:
       - backend



  ostock_pgadmin:
    image: dpage/pgadmin4
    container_name: ostock_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: raj@nola.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  postgres_sql:

networks:
  backend:
    driver: bridge
