spring:
  application:
    name: licence-service
  profiles:
    active: dev
#  cloud:
#    config:
#      uri: http://localhost:8071
management:
  endpoint:
    mappings:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
