version: '3.5'
services:
  postgres:
    container_name: postgres_container
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: pg_database
      PGDATA: /data/postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - /Users/vasylkorol/backaps:/var/opt/postgresql/backup
    ports:
      - "5445:5445"
