server:
  port: 8765
spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8888



management:
  endpoint:
    gateway:
      enabled: true


    beans:
      enabled: true
    mappings:
      enabled: true
  endpoints:

    web:
      exposure:
        include: '*'





#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${random.value}
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#server:
#  port: 0

#logging:
#  pattern:
#    console: '%{1.} [%-5level] %{HH:mm:ss} - %msg%n'





#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: test
#          uri: lb://eclient
#          predicates:
#            - Path=/main/test
#            - Method=GET
#        - id: name
#          uri: lb://eclient2
#          predicates:
#            - Path=/new/name
#            - Method=GET
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka


