server:
  port: 8888


spring:
  application:
    name: github-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vask19/javabegin-config.git
          clone-on-start: true
          username: vask19
          password: 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
          basedir: /Users/vasylkorol/javabeginconfig
          default-label: main

