
spring:
  profiles:
    active: application
  cloud:
    stream:
      bindings:
        todoOutputChannel:
          destination: micro1
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest
