spring:
  application:
    name: config-server
  profiles:
    active:
      - native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
          #git:
          # uri: https://github.com/ihuaylupo/config.git
          #searchPaths: licensingservice
        bootstrap: true

server:
  port: 8071
